//! Parse `cuobjdump --dump-ptx` text output into one [`PtxLine`] per
//! input line — blanks and comments included.
//!
//! PTX carries `.file <id> "<path>"` declarations and
//! `.loc <id> <line> <col>` directives; we propagate the most-recent
//! `.loc` forward to every subsequent line until either a new `.loc`
//! appears or a closing `}` ends the function scope.

use std::collections::HashMap;

use super::types::{PtxLine, SourceLineRef, clone_source_ref};

/// Decode the textual output of `cuobjdump --dump-ptx`.
pub fn parse_ptx_lines(text: &str) -> Vec<PtxLine> {
    let mut files: HashMap<u32, String> = HashMap::new();
    let mut current: Option<SourceLineRef> = None;
    let mut out = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let trimmed = raw.trim_start();
        if let Some((id, path)) = parse_ptx_file_directive(trimmed) {
            files.insert(id, path);
        } else if let Some((file_id, line_no, col)) = parse_ptx_loc_directive(trimmed) {
            current = files.get(&file_id).map(|file| SourceLineRef {
                file: file.clone(),
                line: line_no,
                column: col,
            });
        } else if trimmed.starts_with('}') && current.is_some() {
            current = None;
        }
        let source = if is_ptx_attributable_line(trimmed) {
            current.as_ref().map(clone_source_ref)
        } else {
            None
        };
        out.push(PtxLine {
            line_number: (i as u32).saturating_add(1),
            text: raw.to_string(),
            source,
        });
    }
    out
}

/// `.file <id> "<path>"` — accepts both proto-style integer IDs and
/// the modern cuobjdump form. Returns `None` if the directive doesn't
/// parse.
fn parse_ptx_file_directive(line: &str) -> Option<(u32, String)> {
    let rest = line.strip_prefix(".file ")?;
    let id_end = rest.find(|c: char| c.is_whitespace())?;
    let id_str = rest.get(..id_end)?;
    let id: u32 = id_str.parse().ok()?;
    let after_id = rest.get(id_end..)?.trim_start();
    let quote_start = after_id.find('"')?;
    let after_open = after_id.get(quote_start.checked_add(1)?..)?;
    let quote_end = after_open.find('"')?;
    let path = after_open.get(..quote_end)?.to_string();
    Some((id, path))
}

/// `.loc <file_id> <line> <col>` — column is optional.
fn parse_ptx_loc_directive(line: &str) -> Option<(u32, u32, Option<u32>)> {
    let rest = line.strip_prefix(".loc ")?.trim();
    let mut parts = rest.split_whitespace();
    let file_id: u32 = parts.next()?.parse().ok()?;
    let line_no: u32 = parts.next()?.parse().ok()?;
    let col: Option<u32> = parts.next().and_then(|s| s.parse().ok());
    Some((file_id, line_no, col))
}

/// PTX lines that can carry source attribution: anything that isn't
/// itself a directive (`.foo`) or pure whitespace. Comments still
/// inherit the active `.loc` so an agent walking a single source
/// line gets the surrounding context.
fn is_ptx_attributable_line(line: &str) -> bool {
    if line.is_empty() {
        return false;
    }
    if line.starts_with('.') {
        return false;
    }
    if line == "{" || line == "}" {
        return false;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    use anyhow::Result;

    #[test]
    fn parse_ptx_lines_attaches_loc_to_following_instructions() -> Result<()> {
        let ptx = "\
//
// Generated by NVIDIA NVVM Compiler
//

.version 8.0
.target sm_90
.address_size 64

.file 1 \"/tmp/k.cu\"

.visible .entry _Z3fooP4int(
\t.param .u64 _Z3fooP4int_param_0
)
{
\t.reg .b32 \t%r<2>;
\t.reg .b64 \t%rd<2>;

\t.loc 1 78 4
\tld.param.u64 \t%rd1, [_Z3fooP4int_param_0];
\tcvta.to.global.u64 \t%rd2, %rd1;

\t.loc 1 80 4
\tst.global.u32 \t[%rd2], 1;
\tret;
}
";
        let lines = parse_ptx_lines(ptx);
        // Every input line preserved, including blanks.
        assert_eq!(lines.len(), 25);
        // Directive lines themselves don't carry source
        let loc_line = lines
            .iter()
            .find(|l| l.text.trim_start().starts_with(".loc 1 78"))
            .ok_or_else(|| anyhow::anyhow!("loc 78 line"))?;
        assert!(loc_line.source.is_none());
        // The two instructions after `.loc 1 78 4` are attributed to line 78
        let ld = lines
            .iter()
            .find(|l| l.text.contains("ld.param.u64"))
            .ok_or_else(|| anyhow::anyhow!("ld line"))?;
        let cvta = lines
            .iter()
            .find(|l| l.text.contains("cvta.to.global.u64"))
            .ok_or_else(|| anyhow::anyhow!("cvta line"))?;
        assert_eq!(
            ld.source.as_ref().map(|s| (s.file.as_str(), s.line)),
            Some(("/tmp/k.cu", 78))
        );
        assert_eq!(
            cvta.source.as_ref().map(|s| (s.file.as_str(), s.line)),
            Some(("/tmp/k.cu", 78))
        );
        // After `.loc 1 80 4`, the store is attributed to line 80
        let st = lines
            .iter()
            .find(|l| l.text.contains("st.global.u32"))
            .ok_or_else(|| anyhow::anyhow!("st line"))?;
        assert_eq!(
            st.source.as_ref().map(|s| (s.file.as_str(), s.line)),
            Some(("/tmp/k.cu", 80))
        );
        // Closing `}` clears the scope — the blank/eof afterward has no source
        let close = lines.last().ok_or_else(|| anyhow::anyhow!("last line"))?;
        assert!(close.source.is_none() || close.text.is_empty());
        Ok(())
    }
}
